= Тестування атрибутів якості
:sectlinks:

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

Розділ *Тестування атрибутів якості* описує ключові типи тестування, які допомагають забезпечити надійність, безпеку та високу продуктивність Платформи.

Кожен тип тестування зосереджується на окремому аспекті якості програмного забезпечення.
Цей підхід допомагає виявити потенційні проблеми ще до того, як вони вплинуть на користувачів.

== Що ви знайдете у цьому розділі

🔧 Функціональне тестування ::
Перевіряє, чи працює Платформа так, як очікується. Це тестування гарантує, що всі функції відповідають вимогам і потребам користувачів.

⚙️ Тестування продуктивності ::
Оцінює, як Платформа працює під навантаженням. Воно допомагає виявити слабкі місця й забезпечити масштабованість системи.

🔐 Тестування безпеки ::
Аналізує, наскільки система захищена від зовнішніх і внутрішніх загроз.
Це критичний етап для збереження даних та довіри користувачів.

== Огляд секції

* xref:testing:functional-testing/functional-testing.adoc[Функціональне тестування]
* xref:testing:performance-testing/performance-testing.adoc[Тестування продуктивності]
** xref:testing:performance-testing/perf-report/perf-report-overview.adoc[]
** xref:testing:performance-testing/jmeter-methodology/overview.adoc[Методологія навантажувального тестування (JMeter)]
* xref:testing:security-testing/security-testing.adoc[Тестування безпеки]