// docs/ua/modules/testing/pages/performance-testing/jmeter-methodology/infra-setup/okd-target-cluster-setup.adoc
= Підготовка кластеру OKD до запуску навантажувальних тестів
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

Цей розділ описує кроки підготовки цільового кластера OKD до запуску навантажувального тестування.

[#setup-sign-widget-mock]
== Налаштування mock-сервісу цифрових підписів - sign-widget-mock

На платформі реєстрів використовується - *Підсистема цифрових підписів*.
Це окрема підсистема, яка реалізує пакет операцій по накладанню / перевірці цифрових печаток та перевірці цифрових підписів з метою забезпечення контролю незмінності даних при міжсервісній взаємодії за допомогою спеціалізованих крипто-модулів.

Для навантажувального тестування на платформі реєстрів ми не можемо напряму використовувати підсистему цифрових підписів, це вимагатиме від сотні або тисячі реальних цифрових ключів щоб провести тестування.

Для вирішення даної проблеми з платформою поставляється окремий сервіс - *sign-widget-mock*.
Даний сервіс емулює роботу підсистеми цифрових підписів і дозволяє проводити навантажувальне тестування на платформі реєстрів без використання реальних цифрових ключів.

Після успішного розгортання сервісу *sign-widget-mock* переходимо до наступного кроку - Створення системного користувача SA (Service Account) в OKD для сервісів Jenkins та JMeter

[TIP]
--
Детальніше про підсистему цифрових підписів можна ознайомитись у розділі xref:arch:architecture/registry/operational/digital-signatures/overview[Підсистема цифрових підписів]
--

[#setup-jenkins-jmeter-sa]
== Створення системного користувача SA (Service Account) в OKD для сервісів Jenkins та JMeter




[#setup-configmap-users-mock]
== Створення ConfigMap для mock-сервісу sign-widget-mock